/**
 * Centralized draft-disclaimer copy. Rendered on the creator-page banner,
 * the dashboard note, the PDF footer, and the login screen footnote.
 */

export const DISCLAIMER_FULL =
  "Prelegal generates drafts. Every document is subject to legal review before signing. This is not a substitute for legal advice.";

export const DISCLAIMER_FOOTER =
  "Draft — generated by Prelegal. Subject to legal review. Not a substitute for legal advice.";
